name: custom_text_form_field
description: "This is custom form field for enhancing textfrom_field and give then initial value regax validator"
version: 0.0.7
homepage: https://github.com/rahul12332/custom_text_form_field/blob/main/lib/custom_text_form_field.dart
repository: https://github.com/rahul12332/custom_text_form_field
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# Author Amit Chandra



flutter:


